Added validation for battery charge status.
KickScooterTeam/kick-scooter-vehicle pull request #2
Opened 2020-03-25 14:10 UTC by LeonidBaidak

Need to add handling of javax.validation.ConstraintViolationException.

2020-03-26 18:47 UTC, yakovlieva811 approved these changes

2020-03-26 21:13 UTC, edgar-kr requested changes

2020-03-26 21:13 UTC, edgar-kr commented on src/main/java/com/softserve/kickscooter/kickscootervehicle/management/model/Scooter.java
> +    @Max(value = 100, message = "The battery charge must not exceed than 100%.")
exceed 100%(than is not needed here)

2020-03-26 21:29 UTC, edgar-kr approved these changes

2020-03-29 12:49 UTC, foxrev approved these changes

2020-04-03 15:25 UTC, closed without merging